name: OS

on:
  push:
    branches:
      - '*'
  pull_request: 

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: Install dependencies (Linux/Mac)
      if: runner.os != 'Windows'
      run: npm install
      working-directory: seeql

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: npm install --no-optional
      working-directory: seeql

    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm test
      working-directory: seeql

    - name: Run tests (Mac/Windows)
      if: runner.os != 'Linux'
      run: npm test
      working-directory: seeql
